sky_django/sky_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls',  namespace='catalog')),
    path('users/', include('users.urls',  namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_django/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserProfileView, UserRegisterView, generate_password, confirm_code

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/confirm_code/<str:email>/', confirm_code, name='confirm_code'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/generate_password', generate_password, name='generate_password'),

]

sky_django/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=30, unique=True, verbose_name='Почта')
    verify_code = models.CharField(max_length=10, unique=True, verbose_name='Код верификации')
    avatar = models.ImageField(upload_to='users', verbose_name='аватар', blank=True, null=True)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', blank=True, null=True)
    country = models.CharField(max_length=30, verbose_name='Страна', blank=True, null=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

sky_django/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['readonly'] = True

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'






class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        # self.fields['avatar'].widget.attrs['class'] = 'costom-file-input'

sky_django/users/views.py
import random
import string

from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView

from sky_django import settings
from users.forms import UserProfileForm, UserCreateForm
from users.models import User
from users.utils import generate_code


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'

    def post(self, request, *args, **kwargs):
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        object = User.objects.get(pk=self.kwargs['pk'])
        return object


def confirm_code(request, email):
    if request.method == 'POST':
        verify_code = request.POST.get('verify_code')
        user = User.objects.get(email=email)
        if user.verify_code == verify_code:
            user.is_active = True
            user.save()
            return redirect(reverse('users:login'))
        else:
            raise ValidationError(f'You have used the wrong code!')
    else:
        context = {'title': 'Подтверждение почты'}

    return render(request, 'users/confirm_code.html', context)



class UserRegisterView(CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'users/register.html'

    def get_success_url(self):
        return reverse('users:confirm_code', kwargs={'email': self.object.email})

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save(commit=False)
            code = generate_code()
            new_user.verify_code = code
            new_user.save()
            send_mail(
                subject='Вы зарегистрировались',
                message=code,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )

        return super().form_valid(form)
        # return HttpResponseRedirect(self.success_url)


def generate_password(request):
    symbols = string.ascii_letters
    new_passowrd = ''.join([random.choice(symbols) for _ in range(10)])
    send_mail(
        subject='Смена пароля',
        message=f'Ваш новый пароль {new_passowrd}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_passowrd)
    request.user.save()
    return redirect(reverse('users:login'))

sky_django/users/templates/users/confirm_code.html
{% extends 'catalog/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">


        <div class="col-12">

            <form class="row" method="post">
                {% csrf_token %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>Подтверждение почты</h3>
                        </div>
                        <div class="card-body">
                            <div class="col-auto">
                                <label for="inputPassword6" class="col-form-label">Введите код поддтверждения:</label>
                            </div>
                            <div class="col-auto">
                                <input type="text" id="inputPassword6" class="form-control"
                                       aria-labelledby="passwordHelpInline" name="verify_code">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </div>

                </div>

            </form>
        </div>

    </div>





{% endblock %}

sky_django/users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="container">

        <h1>Авторизация</h1>
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <table>
               {{ form.as_table }}
            </table>
            <input type="submit" value="Войти">
        </form>
        <br>
        <div class="card-footer text-center">
            <div class="bg-light"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>


        </div>
    </div>


{% endblock %}

sky_django/users/templates/users/profile.html
{% extends 'catalog/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">

        <form action="{% url 'users:profile' object.id %} " method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="img-fluid">
                  <img width="150" height="200"
                      src="{% if user.avatar %} {{ user.avatar.url }} {% else %}Нет аватара{% endif %}"

                        class="rounded float-right">
              </div>
        {{ form }}
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>

    <a href="{% url 'users:generate_password' %}" class="btn-warning">Сгенерировать пароль</a>
    </div>





{% endblock %}

sky_django/users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {% for error in form.errors %}
        {{ error | escape }}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="container">
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}

{#        <div class="form-row">#}
{#            <div class="col-md-6">#}
{#                <div class="form-group">#}
{#                    <label class="small mb-1" for="{{ form.phone.id_for_label }}">Телефон</label>#}
{#                    {{ form.phone }}#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-6">#}
{#                <div class="form-group">#}
{#                    <label class="small mb-1" for="{{ form.country.id_for_label }}">Страна</label>#}
{#                    {{ form.country }}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
        <div class="form-row">
            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                        пароля</label>
                    {{ form.password2 }}
                </div>
            </div>
        </div>

        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
        </div>
    </form>
    </div>
{% endblock %}