sky_django/catalog/urls.py
from django.urls import path

from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', ProductList.as_view(), name='product_list'),
    path('contacts/', ContactList.as_view(), name='contact_list'),
    path('contacts/create_contact', ContactCreate.as_view(), name='contact_create'),
    path('detail_product/<int:pk>/', cache_page(60)(ProductDetail.as_view()), name='product_detail'),
    path('update_product/<int:pk>/', UpdateProduct.as_view(), name='update_product'),
    path('create_product/', ProductCreate.as_view(), name='product_form'),
    path('products/delete/<int:pk>/', ProductsDeleteView.as_view(), name='products_delete'),
    path('post_list/', PostList.as_view(), name='post_list'),
    path('detail_post/<int:pk>/', DetailPost.as_view(), name='post_detail'),
    path('create_post/', PostCreate.as_view(), name='post_form'),
    path('update_post/<int:pk>/', PostUpdate.as_view(), name='update_post'),
    path('delete_post/<int:pk>/', DeletePost.as_view(), name='delete_post'),

]

sky_django/sky_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls',  namespace='catalog')),
    path('users/', include('users.urls',  namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sky_django/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserProfileView, UserRegisterView, generate_password, confirm_code

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/confirm_code/<str:email>/', confirm_code, name='confirm_code'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/generate_password', generate_password, name='generate_password'),

]

sky_django/catalog/models.py
from django.db import models
from transliterate import translit

from users.models import User


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='создатель')
    title = models.CharField(max_length=20, verbose_name='Назавание')
    description = models.CharField(max_length=300, verbose_name='Описание')
    image = models.ImageField(upload_to='media', verbose_name='Изображение', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    is_published = models.BooleanField(default=False, verbose_name='опубликованно')

    def __str__(self):
        return f'{self.title} | {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


        permissions = [
                (
                    'set_published',
                    'Can publish products'
                )
            ]


class Version(models.Model):
    product = models.ForeignKey(Product, related_name='versions', on_delete=models.CASCADE, verbose_name='продукт')
    number_version = models.FloatField(verbose_name='Номер версии')
    name_version = models.CharField(max_length=30, verbose_name='Название версии')
    is_active = models.BooleanField(default=False, verbose_name='Активная')

    def save(self, *args, **kwargs):
        versions = Version.objects.filter(product_id=self.product.id)
        for version in versions:
            if version.is_active == True:
                raise ValueError('У продукта уже есть активная версия')
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.product.title}  {self.name_version}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'


class Category(models.Model):
    title = models.CharField(max_length=20, verbose_name='Категория')
    description = models.CharField(max_length=300, verbose_name='Описание')

    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Contact(models.Model):
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    email = models.EmailField()
    site = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return f'{self.phone} | {self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Post(models.Model):
    title = models.CharField(max_length=20, verbose_name='Заголовок')
    slug = models.CharField(max_length=30, verbose_name='Слаг')
    content = models.TextField(verbose_name='Контент')
    preview = models.ImageField(upload_to='media', verbose_name='Изображение', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=False, verbose_name='Опубликованно')
    count_views = models.IntegerField(default=0, verbose_name='Коллчество просмотров')

    def save(self, *args, **kwargs):
        self.slug = translit(self.title, language_code='ru', reversed=True)
        super().save(*args, **kwargs)

    def delete(self, using=None, keep_parents=False):
        self.is_published = False
        self.save()

    def __str__(self):
        return f'{self.title} | {self.content[:30]}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

sky_django/catalog/forms.py
from datetime import datetime

from django import forms
from django.forms import ModelForm, DateTimeInput

from catalog.models import Product, Contact, Post, Version

INCORRECT_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ContactForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('phone', 'email', 'site')

class PostForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'preview', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['is_published'].widget.attrs['class'] = 'form-choice'



class CreateProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'price', 'category', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_published'].widget.attrs['class'] = 'form-choice'
        self.fields['category'].widget.attrs['class'] = 'form-choice'

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title').lower()
        if cleaned_data in INCORRECT_WORDS:
            raise forms.ValidationError('Недопустимое название')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description').lower()
        for item in INCORRECT_WORDS:
            if item in cleaned_data:
                raise forms.ValidationError('Недопустимое слово в описании')
        return cleaned_data


class UpdateProductForm(forms.ModelForm):


    class Meta:
        model = Product
        fields = ('title', 'description', 'image', 'price', 'category', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['is_published'].widget.attrs['class'] = 'form-choice'
        self.fields['category'].widget.attrs['class'] = 'form-choice'




class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('name_version', 'number_version', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['is_active'].widget.attrs['class'] = 'form-choice'

sky_django/catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from catalog.forms import ContactForm, PostForm, CreateProductForm, UpdateProductForm, VersionForm
from catalog.models import Product, Contact, Post, Version
from catalog.service import send_email


@method_decorator(login_required, name='dispatch')
class ProductList(ListView):
    model = Product
    extra_context = {
        'title': 'Список продуктов'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # for item in context['object_list']:
        #     print(item.pk)
        #     context['version'] = Version.objects.filter(product_id=item.pk)

        return context

@method_decorator(login_required, name='dispatch')
class UpdateProduct(UpdateView):
    model = Product
    template_name = 'catalog/update_product.html'
    form_class = UpdateProductForm
    # permission_required = 'catalog.change_product'

    def get_success_url(self):
        return reverse_lazy('catalog:product_detail', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise Http404("Вы не являетесь владельцем продукта.")
        return obj




    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context['formset'] = VersionFormset(data=self.request.POST, instance=self.object)
        else:
            context['formset'] = VersionFormset(instance=self.object)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

class ProductsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:products')


    def test_func(self):
        return self.request.user.is_superuser




@method_decorator(login_required, name='dispatch')
class ProductCreate(CreateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')
    form_class = CreateProductForm

    def form_valid(self, form):
        form = CreateProductForm(data=self.request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = self.request.user
            product.save()
        return HttpResponseRedirect(reverse('catalog:product_list'))


class ContactList(ListView):
    model = Contact
    extra_context = {
        'title': 'Контакты'
    }

class ContactCreate(CreateView):
    model = Contact

    form_class = ContactForm
    template_name = 'catalog/contact_create.html'
    success_url = reverse_lazy('catalog:contact_list')


@method_decorator(login_required, name='dispatch')
class ProductDetail(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = Version.objects.filter(product_id=self.kwargs['pk'])
        for item in context['version']:
            if item.is_active == True:
                context['version'] = item
        return context




class PostList(ListView):
    model = Post
    extra_context = {
        'title': 'Посты'
    }


class DetailPost(DetailView):
    model = Post
    
    def get_object(self, queryset=None):
        object = Post.objects.get(pk=self.kwargs['pk'])
        if object:
            object.count_views += 1
            object.save()
            if object.count_views == 100:
                send_email()
        return object

class PostCreate(CreateView):
    model = Post
    success_url = reverse_lazy('catalog:post_list')
    form_class = PostForm


class PostUpdate(UpdateView):
    model = Post
    template_name = 'catalog/update_post.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse_lazy('catalog:post_detail', kwargs={'pk': self.kwargs['pk']})

class DeletePost(DeleteView):
    model = Post
    success_url = reverse_lazy('catalog:post_list')

sky_django/catalog/templates/catalog/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/main_menu.html' %}


<br>
<br>
<br>
{% block content %}
{% endblock %}


<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

sky_django/catalog/templates/catalog/contact_create.html
{% extends 'catalog/base.html' %}

{% block title %}
    Котакты
{% endblock %}

{% block content %}
    <div class="container">

        <h1>Форма создания контакта</h1>
        <form action="{% url 'catalog:contact_create' %}" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Создать">
        </form>
    </div>

{% endblock %}

sky_django/catalog/templates/catalog/contact_list.html
{% extends 'catalog/base.html' %}

{%  block title %}
Котакты
{%  endblock %}

{% block content %}
    <div class="container">
    <h1>Контакты</h1>
    {%  for obj in object_list %}

        <ul>
        <li>{{ obj.phone }} || {{ obj.email }}</li>
        </ul>
    {%  endfor %}

    <h1>Форма создания контакта</h1>
        <a class="btn-primary" href="{%  url 'catalog:contact_create' %}">Создать контакт</a>

    </div>

{%  endblock %}

sky_django/catalog/templates/catalog/post_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Форма создания поста</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
            Подтверждаете удаление {{ object.title }}?
            </table>
            <input class="btn-danger" type="submit" value="Удалить">

        </form>
    <a type="button" href="{% url 'catalog:post_list' %}"
               class="btn btn-lg btn-block btn-link">Назад</a>
    </div>
{% endblock %}

sky_django/catalog/templates/catalog/post_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <h4 class="bg-info">Заголовок: {{ object.title }}</h4>
        <br>
        <h4 class="bg-info">Контент: {{ object.content }}</h4>
        <br>
        <h4 class="bg-info">Количество просмотров: {{ object.count_views }}</h4>

        <br>
        <h4 class="bg-info">Слаг: {{ object.slug }}</h4>

        <br>
        <h4 class="bg-info">Добавлено: {{ object.created_at }}</h4>

        <br>
        <h4 class="bg-info">Опубликовано: {{ object.is_published }}</h4>

        {% if object.preview %}

            <img src="{{ object.preview.url }}" alt="img" width="100" height="100">
        {% endif %}

    </div>


{% endblock %}

sky_django/catalog/templates/catalog/post_form.html
{% extends 'catalog/base.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Форма создания поста</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <input class="btn-success" type="submit" value="Отправить">
        </form>
    </div>
{% endblock %}

sky_django/catalog/templates/catalog/post_list.html
{% extends 'catalog/base.html' %}

{%  block title %}
{{ title }}
{%  endblock %}

{% block content %}
        <div class="container">
    <h1 class="text-dark">Список постов</h1>

        {% for object in object_list %}
            {% if object.is_published %}

            <div class="row text-center">
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">Название:  {{ object.title }}</h4>
                        </div>
                        {% if object.preview %}

                            <img src="{{ object.preview.url }}" alt="img">
                        {% endif %}
                        <div class="card-body">


                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>Контент: {{ object.content}}</li>

                            </ul>

                            <a type="button" href="{% url 'catalog:post_detail' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детализация</a>
                             <a type="button" href="{% url 'catalog:update_post' object.id %}"
                               class="btn btn-lg btn-block btn-danger">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>

            {% endif %}

        {% endfor %}
        <a class="btn-info" href="{% url 'catalog:post_form' %}">Создать пост</a>
  </div>


{%  endblock %}

sky_django/catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление продукта</h5>
      <form method="post">
        {% csrf_token %}
        Уверены, что хотите удалить продукт "{{ object.name }}"?<br>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog:product_list' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

sky_django/catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <h4 class="bg-info">Создатель: {{ object.user.email }}</h4>
        <h4 class="bg-info">Наименование: {{ object.title }}</h4>
        <br>
        <h4 class="bg-info">Описание: {{ object.description }}</h4>
        <br>
        <h4 class="bg-info">Категория: {{ object.category }}</h4>

        <br>
        <h4 class="bg-info">Цена: {{ object.price }}</h4>

        <br>
        <h4 class="bg-info">Добавлено: {{ object.created_at }}</h4>

        <br>
        <h4 class="bg-info">Обновлено: {{ object.updated_at }}</h4>

        <h4 class="bg-info">Номер версии: {{ version.number_version }}</h4>
        <h4 class="bg-info">Название: {{ version.name_version }}</h4>


        {% if object.image %}

            <img src="{{ object.image.url }}" alt="img" width="100" height="100">
        {% endif %}

    </div>


{% endblock %}

sky_django/catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Форма создания продукта</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <input class="btn-success" type="submit" value="Отправить">
        </form>
    </div>
{% endblock %}

sky_django/catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    {% load short_description %}

    <div class="container">
        <h1 class="text-dark">Список продуктов</h1>

        {% for object in object_list %}

            <div class="row text-center">
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                        </div>
                        {% if object.image %}

                            <img src="{{ object.image.url }}" alt="img">
                        {% endif %}
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>

                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>- {{ object.description | short_description }}</li>


                            {% for ver in object.versions.all %}
                                {% if ver.is_active %}
                                    <li>-Назавание версии: {{ ver.name_version }}</li>
                                    <li>-Номер версии: {{ ver.number_version }}</li>
                                {% endif %}
                            {% endfor %}
                            </ul>


                            <a type="button" href="{% url 'catalog:product_detail' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детализация</a>
                            {% if perms.catalog.change_product %}
                            <a type="button" href="{% url 'catalog:update_product' object.id %}"
                               class="btn btn-lg btn-block btn-danger">Изменить</a>
                        {%  endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{#        <div class="example1-pagination">#}
{#            {% if page_obj.has_previous %}#}
{#                <a class="example1-pagination_link" href="?page=1">&laquo; первая</a>#}
{#                <a class="example1-pagination_link" href="?page={{ page_obj.previous_page_number }}">предыдущая</a>#}
{#            {% endif %}#}
{##}
{#            <span class="example1-pagination_link example1-pagination_link__active">#}
{#            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#            {% if page_obj.has_next %}#}
{#                <a class="example1-pagination_link" href="?page={{ page_obj.next_page_number }}">следующая</a>#}
{#                <a class="example1-pagination_link" href="?page={{ page_obj.paginator.num_pages }}">последняя#}
{#                    &raquo;</a>#}
{#            {% endif %}#}
{#        </div>#}
    </div>
{% endblock %}

sky_django/catalog/templates/catalog/update_post.html
{% extends 'catalog/base.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Форма создания поста</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <input class="btn-success" type="submit" value="Изменить">
            <a type="button" href="{% url 'catalog:delete_post' object.id %}"
               class="btn btn-lg btn-block btn-danger">Удалить</a>
        </form>
    </div>
{% endblock %}

sky_django/catalog/templates/catalog/update_product.html
{% extends 'catalog/base.html' %}

{% block title %} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Форма обновления продукта</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}


            <table>

                {{ form }}

            </table>
            <h1>------------------------------</h1>
            <table>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form }}
                {% endfor %}
            </table>
            <input class="btn-success" type="submit" value="Изменить">
            {% if user.is_superuser %}
                <a type="button" href="{% url 'catalog:delete_post' object.id %}"
                   class="btn btn-lg btn-block btn-danger">Удалить</a>
            {% endif %}
        </form>
    </div>
{% endblock %}